SECRET_KEY = 'this is a secret key. There are others like it, but this one is mine'
STORMPATH_API_KEY_ID = '6RHWJHH7RBRENKGHAEUKKARZH'
STORMPATH_APPLICATION = 'app'
STORMPATH_API_KEY_SECRET = '2Agty3uZzgHJZWGOAJXwtiE6vfBlXKfiGjt/b1BsTSs'
STORMPATH_ENABLE_REGISTRATION = False
UPLOAD_FOLDER = '/george/uploads'
MAX_CONTENT_PATH = 99999
